// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaysqEKeU_mnC384t-_e3zG2qthiSxJMY',
    appId: '1:621872022473:web:44a82cf498cbfee5c9de18',
    messagingSenderId: '621872022473',
    projectId: 'fixmate-2bfe9',
    authDomain: 'fixmate-2bfe9.firebaseapp.com',
    storageBucket: 'fixmate-2bfe9.firebasestorage.app',
    measurementId: 'G-ZD3242QPG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4cwGbRQL_BbGQNMZh7T6Xn5bZWlYSZ18',
    appId: '1:621872022473:android:2ebc816786c50bc8c9de18',
    messagingSenderId: '621872022473',
    projectId: 'fixmate-2bfe9',
    storageBucket: 'fixmate-2bfe9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDphMqWjBNldDi4LM8lvkm1TG_b5Tgb0EQ',
    appId: '1:621872022473:ios:1efacf269c03780bc9de18',
    messagingSenderId: '621872022473',
    projectId: 'fixmate-2bfe9',
    storageBucket: 'fixmate-2bfe9.firebasestorage.app',
    iosBundleId: 'com.example.fixmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDphMqWjBNldDi4LM8lvkm1TG_b5Tgb0EQ',
    appId: '1:621872022473:ios:1efacf269c03780bc9de18',
    messagingSenderId: '621872022473',
    projectId: 'fixmate-2bfe9',
    storageBucket: 'fixmate-2bfe9.firebasestorage.app',
    iosBundleId: 'com.example.fixmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaysqEKeU_mnC384t-_e3zG2qthiSxJMY',
    appId: '1:621872022473:web:22ba748a7ac51c48c9de18',
    messagingSenderId: '621872022473',
    projectId: 'fixmate-2bfe9',
    authDomain: 'fixmate-2bfe9.firebaseapp.com',
    storageBucket: 'fixmate-2bfe9.firebasestorage.app',
    measurementId: 'G-YT96Z8960G',
  );
}
